[project]
name = "nsqip-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.6.0",
    "jupyter>=1.1.1",
    "chardet>=5.2.0",
]
